<?php
/**
 * @var $this \angelokezimana\elephpant\View
 */
$this->title = 'Contact'
?>
<h1>ELEPHPANT Project - contact</h1>

<?php $form = \angelokezimana\elephpant\form\Form::begin('', "post"); ?>

    <?= $form->field($model, 'subject') ?>
    <?= $form->field($model, 'email') ?>
    <?= new \angelokezimana\elephpant\form\TextareaField($model, 'body') ?>
    <button type="submit" class="btn btn-info">Submit</button>

<?php \angelokezimana\elephpant\form\Form::end(); ?>
