<?php
/**
 * @var $this \app\core\View
 */
$this->title = 'Contact'
?>
<h1>ELEPHPANT Project - contact</h1>

<?php $form = \app\core\form\Form::begin('', "post"); ?>

    <?= $form->field($model, 'subject') ?>
    <?= $form->field($model, 'email') ?>
    <?= new \app\core\form\TextareaField($model, 'body') ?>
    <button type="submit" class="btn btn-info">Submit</button>

<?php \app\core\form\Form::end(); ?>
