<h1>Register</h1>

<form method="post">
    <div class="form-group">
        <label>Full Name</label>
        <input type="text" name="subject" class="form-control">
    </div>
    <div class="form-group">
        <label>E-mail</label>
        <input type="email" name="email" class="form-control">
    </div>
    <div class="form-group">
        <label>Password</label>
        <input type="password" name="password" class="form-control">
    </div>
    <div class="form-group">
        <label>Confirm password</label>
        <input type="password" name="confirm_password" class="form-control">
    </div>
    <button type="submit" class="btn btn-info">Submit</button>
</form>
