<?php
/**
 * @var $this \angelokezimana\elephpant\View
 */
$this->title = 'Register'
?>
<h1>Register</h1>

<?php $form = \angelokezimana\elephpant\form\Form::begin('', "post"); ?>

    <?= $form->field($model, 'full_name') ?>
    <?= $form->field($model, 'email') ?>
    <?= $form->field($model, 'password')->passwordField() ?>
    <?= $form->field($model, 'confirm_password')->passwordField() ?>
    <button type="submit" class="btn btn-info">Submit</button>

<?php \angelokezimana\elephpant\form\Form::end(); ?>
